services:
  - type: web
    name: hotel-booking-django
    runtime: python
    buildCommand: ./build.sh
    startCommand: gunicorn core.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
