# Generated by Django 6.0.6 on 2026-07-05 18:15

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم الفندق')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('address', models.CharField(max_length=300, verbose_name='العنوان')),
                ('phone', models.CharField(max_length=20, verbose_name='رقم الهاتف')),
                ('email', models.EmailField(max_length=254, verbose_name='البريد الإلكتروني')),
                ('website', models.URLField(blank=True, verbose_name='الموقع الإلكتروني')),
                ('image', models.URLField(blank=True, verbose_name='رابط الصورة')),
                ('rating', models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='التقييم')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'فندق',
                'verbose_name_plural': 'الفنادق',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=10, verbose_name='رقم الغرفة')),
                ('room_type', models.CharField(choices=[('single', 'غرفة مفردة'), ('double', 'غرفة مزدوجة'), ('suite', 'جناح'), ('deluxe', 'ديلوكس')], max_length=20, verbose_name='نوع الغرفة')),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='السعر لليلة')),
                ('capacity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='السعة (عدد الأشخاص)')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('is_available', models.BooleanField(default=True, verbose_name='متاحة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='hotels.hotel', verbose_name='الفندق')),
            ],
            options={
                'verbose_name': 'غرفة',
                'verbose_name_plural': 'الغرف',
                'ordering': ['room_number'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateField(verbose_name='تاريخ الوصول')),
                ('check_out', models.DateField(verbose_name='تاريخ المغادرة')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='السعر الإجمالي')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('confirmed', 'مؤكد'), ('cancelled', 'ملغي'), ('completed', 'مكتمل')], default='confirmed', max_length=20, verbose_name='الحالة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='hotels.room', verbose_name='الغرفة')),
            ],
            options={
                'verbose_name': 'حجز',
                'verbose_name_plural': 'الحجوزات',
                'ordering': ['-created_at'],
            },
        ),
    ]
